# Generated by Django 5.2.8 on 2025-11-07 17:34

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BillingPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('billing_type', models.CharField(choices=[('subscription', 'Subscription'), ('pay_per_call', 'Pay Per Call')], max_length=20)),
                ('monthly_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('api_calls_limit', models.IntegerField(blank=True, null=True)),
                ('transaction_limit', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('per_call_cost', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('features', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'billing_plans',
            },
        ),
        migrations.CreateModel(
            name='APIKey',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('key', models.CharField(db_index=True, max_length=255, unique=True)),
                ('secret', models.CharField(max_length=255, unique=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('revoked', 'Revoked')], default='active', max_length=10)),
                ('last_used', models.DateTimeField(blank=True, null=True)),
                ('ip_whitelist', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_keys', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'api_keys',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('login', 'Login'), ('logout', 'Logout'), ('create_api_key', 'Create API Key'), ('revoke_api_key', 'Revoke API Key'), ('update_profile', 'Update Profile'), ('create_webhook', 'Create Webhook'), ('delete_webhook', 'Delete Webhook'), ('update_payment_provider', 'Update Payment Provider')], max_length=50)),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField(blank=True)),
                ('details', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'audit_logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('plan', models.CharField(choices=[('starter', 'Starter'), ('growth', 'Growth'), ('enterprise', 'Enterprise')], default='starter', max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], default='active', max_length=20)),
                ('stripe_subscription_id', models.CharField(blank=True, max_length=255)),
                ('current_period_start', models.DateTimeField()),
                ('current_period_end', models.DateTimeField()),
                ('renewal_date', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'subscriptions',
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('invoice_number', models.CharField(max_length=50, unique=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('issued', 'Issued'), ('paid', 'Paid'), ('overdue', 'Overdue'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('tax', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total', models.DecimalField(decimal_places=2, max_digits=15)),
                ('due_date', models.DateField()),
                ('paid_date', models.DateField(blank=True, null=True)),
                ('payment_method', models.CharField(blank=True, max_length=50)),
                ('stripe_invoice_id', models.CharField(blank=True, max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'invoices',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(blank=True, max_length=255)),
                ('country', models.CharField(choices=[('NG', 'Nigeria'), ('GH', 'Ghana'), ('KE', 'Kenya'), ('UG', 'Uganda'), ('TZ', 'Tanzania'), ('ET', 'Ethiopia'), ('ZA', 'South Africa'), ('US', 'United States'), ('GB', 'United Kingdom'), ('CA', 'Canada')], default='NG', max_length=2)),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('business_type', models.CharField(blank=True, max_length=100)),
                ('developer_type', models.CharField(blank=True, choices=[('individual', 'Individual Developer'), ('startup', 'Startup'), ('enterprise', 'Enterprise'), ('agency', 'Agency'), ('other', 'Other')], max_length=20)),
                ('preferred_currency', models.CharField(choices=[('NGN', 'Nigerian Naira'), ('GHS', 'Ghanaian Cedi'), ('KES', 'Kenyan Shilling'), ('UGX', 'Ugandan Shilling'), ('TZS', 'Tanzanian Shilling'), ('ETB', 'Ethiopian Birr'), ('ZAR', 'South African Rand'), ('USD', 'US Dollar'), ('GBP', 'British Pound'), ('EUR', 'Euro'), ('CAD', 'Canadian Dollar')], default='USD', max_length=3)),
                ('kyc_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_profiles',
            },
        ),
        migrations.CreateModel(
            name='Webhook',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('url', models.URLField()),
                ('event_types', models.JSONField(default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('secret', models.CharField(max_length=255, unique=True)),
                ('retry_count', models.IntegerField(default=0)),
                ('last_triggered', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webhooks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'webhooks',
            },
        ),
        migrations.CreateModel(
            name='WebhookEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(max_length=50)),
                ('payload', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('response_status_code', models.IntegerField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('attempt', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('webhook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='api.webhook')),
            ],
            options={
                'db_table': 'webhook_events',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='APILog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('endpoint', models.CharField(max_length=255)),
                ('method', models.CharField(max_length=10)),
                ('status_code', models.IntegerField()),
                ('response_time', models.FloatField()),
                ('request_size', models.BigIntegerField(default=0)),
                ('response_size', models.BigIntegerField(default=0)),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField(blank=True)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('api_key', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='api.apikey')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'api_logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='api_logs_user_id_b90c54_idx'), models.Index(fields=['api_key', '-created_at'], name='api_logs_api_key_198042_idx')],
            },
        ),
        migrations.CreateModel(
            name='KYCVerification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('verification_type', models.CharField(choices=[('bvn', 'Bank Verification Number'), ('nin', 'National Identification Number'), ('account', 'Account Verification')], max_length=20)),
                ('verification_id', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('failed', 'Failed'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('provider', models.CharField(max_length=20)),
                ('provider_reference', models.CharField(max_length=255, unique=True)),
                ('verification_data', models.JSONField(default=dict)),
                ('error_message', models.TextField(blank=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kyc_verifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'kyc_verifications',
                'unique_together': {('user', 'verification_type')},
            },
        ),
        migrations.CreateModel(
            name='PaymentProvider',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(choices=[('paystack', 'Paystack'), ('flutterwave', 'Flutterwave'), ('stripe', 'Stripe'), ('mono', 'Mono'), ('okra', 'Okra'), ('chapa', 'Chapa'), ('lazerpay', 'Lazerpay')], max_length=20)),
                ('public_key', models.CharField(max_length=500)),
                ('secret_key', models.CharField(max_length=500)),
                ('is_live', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('webhook_url', models.URLField(blank=True)),
                ('webhook_secret', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_providers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'payment_providers',
                'unique_together': {('user', 'provider')},
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(choices=[('paystack', 'Paystack'), ('flutterwave', 'Flutterwave'), ('stripe', 'Stripe'), ('mono', 'Mono'), ('okra', 'Okra'), ('chapa', 'Chapa'), ('lazerpay', 'Lazerpay')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('currency', models.CharField(choices=[('NGN', 'Nigerian Naira'), ('GHS', 'Ghanaian Cedi'), ('KES', 'Kenyan Shilling'), ('UGX', 'Ugandan Shilling'), ('TZS', 'Tanzanian Shilling'), ('ETB', 'Ethiopian Birr'), ('ZAR', 'South African Rand'), ('USD', 'US Dollar'), ('CAD', 'Canadian Dollar')], default='NGN', max_length=3)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded')], default='pending', max_length=20)),
                ('reference', models.CharField(db_index=True, max_length=255, unique=True)),
                ('customer_email', models.EmailField(max_length=254)),
                ('customer_phone', models.CharField(blank=True, max_length=20)),
                ('description', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('fee', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('net_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('provider_response', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('idempotency_key', models.CharField(blank=True, db_index=True, max_length=255, null=True, unique=True)),
                ('stripe_payment_method_id', models.CharField(blank=True, max_length=255)),
                ('api_key', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='api.apikey')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'transactions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='transaction_user_id_ced08a_idx'), models.Index(fields=['status', '-created_at'], name='transaction_status_b84006_idx'), models.Index(fields=['reference'], name='transaction_referen_c33c6b_idx'), models.Index(fields=['idempotency_key'], name='transaction_idempot_d892f2_idx')],
            },
        ),
        migrations.CreateModel(
            name='UsageMetric',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('period_start', models.DateTimeField()),
                ('period_end', models.DateTimeField()),
                ('api_calls', models.BigIntegerField(default=0)),
                ('transaction_volume', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('data_transferred_mb', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('cost', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('api_key', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.apikey')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_metrics', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'usage_metrics',
                'unique_together': {('user', 'period_start', 'period_end')},
            },
        ),
    ]
