# Generated by Django 5.2.8 on 2025-11-10 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_transaction_settlement'),
    ]

    operations = [
        migrations.AddField(
            model_name='apikey',
            name='key_hash',
            field=models.CharField(blank=True, max_length=256, null=True, unique=True),
        ),
    ]
