# Generated by Django 5.2.8 on 2025-11-10 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_apikey_key_hash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apikey',
            name='key_hash',
            field=models.CharField(blank=True, db_index=True, max_length=256, null=True, unique=True),
        ),
    ]
