# Generated by Django 5.2.8 on 2025-11-11 14:42
# IMPORTANT: This migration deletes old billing models
# Run 0007a_migrate_billing_data.py FIRST to preserve data!

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007a_migrate_billing_data'),  # Run data migration first!
    ]

    operations = [
        migrations.DeleteModel(
            name='BillingPlan',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='subscription',
        ),
        migrations.DeleteModel(
            name='Subscription',
        ),
    ]
