# Generated by Django 5.2.8 on 2025-11-11 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_billingsubscription_feature_payment_paymentattempt_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BillingPlan',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='subscription',
        ),
        migrations.DeleteModel(
            name='Subscription',
        ),
    ]
