# Generated by Django 5.2.8 on 2025-11-20 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_cleanup_indexes'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='webhookdeliverylog',
            new_name='webhook_del_webhook_e82b2f_idx',
            old_name='webhook_del_webhook_idx',
        ),
        migrations.RenameIndex(
            model_name='webhookdeliverylog',
            new_name='webhook_del_status_cc0947_idx',
            old_name='webhook_del_status_idx',
        ),
        migrations.RenameIndex(
            model_name='webhookdeliverylog',
            new_name='webhook_del_event_i_f21fcd_idx',
            old_name='webhook_del_event_i_idx',
        ),
        migrations.RenameIndex(
            model_name='webhookdeliverylog',
            new_name='webhook_del_next_re_fa8c0f_idx',
            old_name='webhook_del_next_re_idx',
        ),
        migrations.RenameIndex(
            model_name='webhookevent',
            new_name='webhook_eve_provide_3503e3_idx',
            old_name='webhook_eve_provide_idx',
        ),
        migrations.RenameIndex(
            model_name='webhookevent',
            new_name='webhook_eve_canonic_790910_idx',
            old_name='webhook_eve_canonic_idx',
        ),
        migrations.RenameIndex(
            model_name='webhookevent',
            new_name='webhook_eve_process_1085da_idx',
            old_name='webhook_eve_process_idx',
        ),
        migrations.RenameIndex(
            model_name='webhooksubscription',
            new_name='webhook_sub_user_id_1c6876_idx',
            old_name='webhook_sub_user_id_idx',
        ),
        migrations.RenameIndex(
            model_name='webhooksubscription',
            new_name='webhook_sub_active_b2cf29_idx',
            old_name='webhook_sub_active_idx',
        ),
        migrations.AddIndex(
            model_name='webhookevent',
            index=models.Index(fields=['provider_event_id'], name='webhook_eve_provide_ef7be8_idx'),
        ),
    ]
