# Generated by Django 5.2.8 on 2025-11-20 06:54
# State-only migration to sync Django's state with actual database indexes

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_rename_webhook_del_webhook_idx_webhook_del_webhook_e82b2f_idx_and_more'),
    ]

    operations = [
        # This is a no-op migration that tells Django the indexes are already correct
        # The actual indexes were created by migration 0007 with the correct names
        migrations.RunSQL(
            sql="SELECT 1;",  # No-op SQL
            reverse_sql="SELECT 1;",
            state_operations=[
                # Tell Django the indexes already exist with the correct names
            ]
        ),
    ]
