# Generated by Django 5.2.8 on 2025-11-20 09:01

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20251120_0054'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=255)),
                ('business_phone', models.CharField(blank=True, max_length=20)),
                ('business_type', models.CharField(blank=True, choices=[('sole_proprietorship', 'Sole Proprietorship'), ('partnership', 'Partnership'), ('llc', 'Limited Liability Company'), ('corporation', 'Corporation'), ('nonprofit', 'Non-Profit'), ('other', 'Other')], max_length=50)),
                ('country', models.CharField(choices=[('NG', 'Nigeria'), ('GH', 'Ghana'), ('KE', 'Kenya'), ('UG', 'Uganda'), ('TZ', 'Tanzania'), ('ET', 'Ethiopia'), ('ZA', 'South Africa'), ('US', 'United States'), ('GB', 'United Kingdom'), ('CA', 'Canada')], default='NG', max_length=2)),
                ('business_email', models.EmailField(blank=True, max_length=254)),
                ('business_address', models.TextField(blank=True)),
                ('tax_id', models.CharField(blank=True, max_length=100)),
                ('website', models.URLField(blank=True, validators=[django.core.validators.URLValidator()])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='business_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'business_profiles',
            },
        ),
        migrations.CreateModel(
            name='PaymentProviderConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(choices=[('paystack', 'Paystack'), ('flutterwave', 'Flutterwave'), ('stripe', 'Stripe')], max_length=20)),
                ('public_key_encrypted', models.TextField()),
                ('secret_key_encrypted', models.TextField()),
                ('mode', models.CharField(choices=[('test', 'Test Mode'), ('live', 'Live Mode')], default='test', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('is_primary', models.BooleanField(default=False)),
                ('credentials_validated', models.BooleanField(default=False)),
                ('last_validated_at', models.DateTimeField(blank=True, null=True)),
                ('validation_error', models.TextField(blank=True)),
                ('webhook_url', models.URLField(blank=True)),
                ('webhook_secret', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provider_configs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'payment_provider_configs',
                'indexes': [models.Index(fields=['user', 'is_active', 'is_primary'], name='payment_pro_user_id_7d9c24_idx')],
                'unique_together': {('user', 'provider', 'mode')},
            },
        ),
    ]
