# Generated by Django 5.2.8 on 2025-11-26 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_businessprofile_paymentproviderconfig'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BillingPlan',
        ),
        migrations.RemoveField(
            model_name='webhook',
            name='user',
        ),
        migrations.DeleteModel(
            name='Subscription',
        ),
        migrations.DeleteModel(
            name='Webhook',
        ),
    ]
